[package]
name = "pi-providers"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["rustls-tls"]
native-tls = ["pi-ai/native-tls", "reqwest/native-tls"]
rustls-tls = ["pi-ai/rustls-tls", "reqwest/rustls-tls"]

[dependencies]
pi-ai = { path = "../pi-ai", default-features = false }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
